### PR TITLE
CORS Prefix Feature

### PR DESCRIPTION
**Pull request by sivakusayan**
Using this library in the browser normally results in CORS issues when attempting to fetch data. This feature attempts to provide a workaround by allowing the user to prefix the URL with a CORS proxy of their choice.

I modified the URL builder to account for a corsUrl variable, and the fetch functions to take in the corsUrl as their last argument.

### CODE REVIEW

**Comment by sivakusayan** [comment]
Gotcha - I changed the names of the properties so they should be more general now.
Also what do you mean by the parameter type should be optional as the parameter is optional? I think that the customBaseUrl property in UrlBuilder is already optional, unless you mean something else.

**Comment by FelixRilling** [comment]
The names look good now!

The parameters are _technically_ optional already, but in typescript you can use the `?` to declare that as well: https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters

Int this case:
```typescript
const fetchFormats = async (
    timeframe: ITimeframeData,
    useMonotype: boolean = false,
    corsUrl: string
    customBaseUrl?: string // Added '?'
): Promise<IFormatsData> => {
// Omitted
}

**Comment by sivakusayan** [comment]
Haha, no its fine ^^

I got confused as I thought I did that already, but it turns out I only made it optional in the types folder and not in the src folder. Everything should be fixed now, my bad for that.

**Comment by FelixRilling** [comment]
Thanks a ton! I will publish a new release with your changes in a bit.

**Pull request merged**
